from flask import Blueprint, jsonify, request, current_app
from database import db
from models import Timetable, TimetableEntry, User
import jwt
from functools import wraps

timetable_bp = Blueprint('timetable_bp', __name__)

def token_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token = request.headers.get('Authorization')
        if not token:
            return jsonify({'error': 'Token is missing'}), 401
        
        try:
            if token.startswith('Bearer '):
                token = token.split(' ')[1]
            data = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
            current_user = User.query.get(data['user_id'])
            if not current_user:
                return jsonify({'error': 'User not found'}), 401
        except Exception as e:
            return jsonify({'error': 'Token is invalid'}), 401
        
        return f(current_user, *args, **kwargs)
    return decorated

@timetable_bp.route('/api/timetables/my', methods=['GET'])
@token_required
def get_my_timetables(current_user):
    """Get all timetables generated by the current user"""
    timetables = Timetable.query.filter_by(user_id=current_user.id).order_by(Timetable.created_at.desc()).all()
    return jsonify([t.to_dict() for t in timetables]), 200

@timetable_bp.route('/api/timetables/<int:id>', methods=['GET'])
@token_required
def get_timetable_details(current_user, id):
    """Get details of a specific timetable, ensuring ownership"""
    timetable = Timetable.query.get(id)
    
    if not timetable:
        return jsonify({'error': 'Timetable not found'}), 404
        
    # Isolation Check
    if timetable.user_id != current_user.id and current_user.role != 'admin':
        return jsonify({'error': 'Unauthorized access to this timetable'}), 403
        
    return jsonify({
        'timetable': timetable.to_dict(),
        'entries': [e.to_dict() for e in timetable.entries]
    }), 200
