services:
  - type: web
    name: timetable-generator
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: NODE_VERSION
        value: 18.17.0
